sudo: required
services:
- docker
env:
  global:
  - VERSIONS="5.6,7.0,7.1"
  - secure: eKF/LOnadld5ddnW9OtWQNaI3CedA+YVlMHTi9XI8M/cclOL5tgid62BFdYU4g4lmTqK2NcafYNaNLrCsQW5PxeC9udVvhvyE5SVYxDldB/nT63/4osspYsT374KaMjle6redWRbJzwXlh9ikzRPalxtLdd/dZdS+Y0tBKDA4Bjt7c8wzzKufLx8HpTk5znbIdHGLKGpkOM5bcXqJzLvI3TDdh7sJzPZm7Tgoy2MedU+jKPKwmyh6PJcbb4FGrnxeYEPrvDZ80qZRmrXCcTBRAdSHSh8Ucc257+jYkJ38JXgu4TbRvuzZaehSRaSfP/qMHMa4igPzKZHPWPUyMHev5xji/j2JfvNH4slrA/7t3Ppbr0tQwaPphyzzV+jWNmYMjEvBFe0lRh9fsJhs8gKjIZe4r8uq7s+CyGH7Q+KfmNWKiL9hSxcF4YX33/gEjyXsa9X/rLkhiVNi8j6ITeDAxOJx7P/qB762yeZA+O+eEyVkoVeDIJ2cIbrrZPj9/g+HA+vt7akSfrOt1zf65Hnw0S7kl5EXRLywycUewXDPcBzQYLLEM3k8awFqxQlbxbMQ1NdVSYq3fMrH5Txpcawk/wJ5WghT30JNLU5RgQHzhz1uB2MkKZdOL8uXfwjL8r3bgLTXn56EmVlOpOLzAOb4jvhsl9e/VdMQpbINj88+2E=
script:
- ". test/run"
notifications:
  slack:
    secure: BQhBiSRib4fa/hI947xYdUQ+kILcR7ps5dceUABCHlqq/YLesVLxo2dRIW9GhLsfcPOFN5/BOKex1B/HTtHjEjq68EiM4e4SQkiFp+dTI4OflqDQ9xEvob9fhyHjLzD4bKnpWXAlnndBEGrgFNAT9DuAh3S2IciNiXOLeeF3/BZNXXjtK2rzFoz6su0CSxIeHkjUwaKp9ymm1FtK1DHf+gMUExpYGxoFkbrSdBrXU5Es8bwiEVl548VPqbb+tADfgoX9fvLj8GyCnCCC7zPEHPPRV/s53HPvwm3ZMT2UsZmjv3JEjTDLTpfD3dduXHdu0VYvKVuIShZDcJsZn77ZH2+a9BajCOKEx/dCvEaILZ6/fbELh/U3/4mep1oe1ctDtL1lnqrU5x9l4FAmdOxE6K63X/R8HWjYM1rcPizMsmBFxekCxaAZpW3fVSrfbvK2poL2dQ3GnTuHx7GXql3z27L9F1/BZOVCjw3Nl7Yux9M+FsFGU8CKk6kpntS2q0FwABchn4bRnHT80Jbavcv+E7ZT2S93v3ubrH98OhxamNESUcNAoBkcxWgI17pwbBDhXbjqsIhyAFJLegn3JWd2vBXeMChs301sgHLEyWe/9u/M1uQJC+MsePy1Y0Mcn0GPYbVIKW0iwlIVu+yM2T8dZ5BiyRxYpZrqjVtTIJqAMz8=
